=pod

=for HTML <a href="https://travis-ci.org/briang/p5-bit-twiddling"><img src="https://api.travis-ci.org/briang/p5-bit-twiddling.svg?branch=master"></a>

=for HTML <a href="https://ci.appveyor.com/api/project/briang/p5-bit-twiddling"><img src="https://ci.appveyor.com/api/projects/status/github/briang/p5-bit-twiddling?branch=master&svg=true"></a>

=for HTML <a href='https://coveralls.io/github/briang/p5-bit-twiddling?branch=master'><img src='https://coveralls.io/repos/github/briang/p5-bit-twiddling/badge.svg?branch=master' alt='Coverage Status' /></a>

=head1 Bit::Twiddling

Version 0.10

=head2 INSTALLATION

To install this module, run the following commands:

    perl Makefile.PL
    make
    make test
    make install

Or, just use your favorite CPAN client

    cpanm Bit::Twiddling

=head2 DEPENDENCIES

This module requires a C compiler, but has no other build
dependencies. For testing, Test::Warn is required.

=head2 COPYRIGHT AND LICENCE

Copyright (C) 2018, Brian Greenfield

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.
